# config/gateway.config.yml

# http
http:
  port: 1000
  host: localhost
# apiEndpoints
apiEndpoints:
  bus:
    host: 'localhost'
    paths: "/v1/bus/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

  customer:
    host: 'localhost'
    paths: "/v1/customer/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

    employees:
    host: 'localhost'
    paths: "/v1/employees/*"
    methods: ["GET", "POST", "PUT", "DELETE"]

# serviceEndpoints
serviceEndpoints:
  busService:
    url: "http://localhost:3003/"

  customerService:
    url: "http://localhost:3002/"

  employeesService:
    url: "http://localhost:3001/"


# policies
policies:
  - cors
  - log
  - jwt
  - proxy

# pipelines
pipelines:
  busPipeline:
    apiEndpoints:
      - bus
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET,PUT,PATCH,POST,DELETE'
      - log:
          - action: 
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: busService
              changeOrigin: true
  
  customerPipeline:
    apiEndpoints:
      - customer
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET,PUT,PATCH,POST,DELETE'
      # - jwt:
      #     - action:
      #         secretOrPublicKey: 'nodeTypescript'
      #         checkCredentialExistence: false
      - log:
          - action: 
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: customerService
              changeOrigin: true

    employeesPipeline:
    apiEndpoints:
      - employees
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'GET,PUT,PATCH,POST,DELETE'
      # - jwt:
      #     - action:
      #         secretOrPublicKey: 'nodeTypescript'
      #         checkCredentialExistence: false
      - log:
          - action: 
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: employeesService
              changeOrigin: true
